---
title: "Onboarding-programming"
output: html_document
date: "2024-02-16"
---

## Very useful materials

- Programming norms and docs at RWE [Sharepoint](https://umcutrecht.sharepoint.com/:f:/s/W_JC_RWE-groupSturkenboom/EgjWw_lelAtOhf0hmrcJ510BxJhin_gCo1qBUuhiH-0qIA?e=4C3hq3)

- To develop a new repo: [Repo template](https://github.com/UMC-Utrecht-RWE/repo_template)

- Package of common functions [T2-DataManagementModel](https://github.com/UMC-Utrecht-RWE/T2-DataManagementModel)

- 
## A mini task

To get started on a new project repo:

1. Create a repo ZZZ named after the project and pull onto local machine.
2. Download [Repo template](https://github.com/UMC-Utrecht-RWE/repo_template) and copy the content into ZZZ, commit and push.
3. Add module [T2-DataManagementModel](https://github.com/UMC-Utrecht-RWE/T2-DataManagementModel) into ZZZ as a subsidiary package, the common functions are going to be utilized in ZZZ.
4. Add a set of sample data from [Synthetic database](https://umcutrecht.sharepoint.com/sites/W_JC_RWE-groupSturkenboom/Gedeelde%20documenten/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FW%5FJC%5FRWE%2DgroupSturkenboom%2FGedeelde%20documenten%2FGeneral%2F04%2E%20Documentation%2FSynthetic%20databases&viewid=648f81c8%2D4042%2D415e%2Daa4c%2Da2541bd74a3f) into folder ZZZ/data/D2_cdm
5. Run code ZZZ/transformations/common_functionality/set_project_dirs.R locally to produce a set of directory strings.
6. Based on the values, change the directories accordingly in repo T2-DataManagementModel script [set_database.R](https://github.com/UMC-Utrecht-RWE/T2-DataManagementModel/blob/main/R/scripts/set_database.R). 
 
    1. Issue raised: found typos in file set_database.R: directoreis are specified differently from results generated by running set_project_dirs.R
    2. Issue rectified: modify set_database.R
    3. Changes recorded in commit history [Update set_database.R](https://github.com/UMC-Utrecht-RWE/T2-DataManagementModel/commit/857449f0db275a45631634efa7cf7bc08c58dc78) and [minor changes to variable names](https://github.com/UMC-Utrecht-RWE/T2-DataManagementModel/commit/c6e2fb01a57a5555e2f7eff912cf3c3ad7332ec8)
  